### ISSUE TITLE
Osmotic Enchanter does not actually enchant [when accidentally constructed with Botania Smokey Quartz].

### ISSUE THREAD

**Issue by Kiithnaras** [Thaumic-Tinkerer/ThaumicTinkerer#1015]
Having successfully formed the multiblock, holding the appropriate vis crystals, and having ample vis to enchant with (ca. 1600), pressing the Start Enchanting button consumes the vis crystals, but does not actually consume aura vis nor does it successfully enchant.

![image](https://user-images.githubusercontent.com/2756235/81605083-ec7dba80-939e-11ea-9e44-bcd684f7048a.png)

The following error prints to the console when the Start Enchanting button is pressed.

```
[15:41:16] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

Using TT v 5.0 Beta 1.1

- - - - - - - - - -
UPDATE: Apparently this issue is related to Botania Smoky Quartz blocks being used instead of Thaumic Tinkerer Black Quartz. When constructed thus, the multiblock still forms normally, but the enchanter behaves inappropriately as described above. Thankfully, the Smoky Quartz can be removed and replaced with the appropriate Black Quartz blocks without destroying the multiblock.

**Comment by nekosune** [comment]
Please upload the full error log.

**Comment by Kiithnaras** [comment]
Full log as requested.

[2020-05-10-3.log](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/files/4612457/2020-05-10-3.log)

**Comment by nekosune** [comment]
Not giving up on this, but I find myself unable to reproduce as yet

**Comment by Kiithnaras** [comment]
No idea what to make of this, then. I've updated TT to the latest, updated Java to the latest, and updated Forge to a more recent version used in another modpack (14.23.2847). It still prints the error when attempting to enchant. Perhaps Forge isn't up-to-date enough, or perhaps there is some mod conflict somewhere (using Enigmatica 2 Expert 1.67, but with a few customizations and individual updates).

```

[21:07:32] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
```
<details>
  <summary>Modlist:</summary>
```
  [✔️] ActuallyAdditions-1.12.2-r148
  [✔️] ActuallyBaubles-1.12-1.1
  [✔️] AdvancedRocketry-1.12.2-1.5.0-139-universal
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AE2WTLib-1.12.2-1.0.6
  [✔️] AIImprovements-1.12-0.0.1b3
  [✔️] AkashicTome-1.2-12
  [✔️] angermanagement-1.12.2-1.0.2
  [✔️] animania-1.12.2-1.6.2
  [✔️] Animus-1.12-2.1.4
  [✔️] AppleCore-mc1.12.2-3.2.0
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] appliedenergistics2-rv6-stable-6
  [✔️] architecturecraft-1.12-3.80
  [✔️] armoreablemobs-1.12.2-1.1.8
  [✔️] astralsorcery-1.12.2-1.10.19
  [✔️] AutoPickup-1.12-2.5.1
  [✔️] AutoRegLib-1.3-31
  [✔️] Avaritia-1.12.2-3.3.0.33-universal
  [✔️] backpack-3.0.2-1.12.2
  [✔️] badwithernocookiereloaded-1.12.2-3.3.16
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterBuildersWands-1.12.2-0.13.2.271+5997513
  [✔️] BetterFps-1.4.8
  [✔️] BetterQuesting-3.5.300
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2441-universal
  [✔️] blockcraftery-1.12.2-1.3.1
  [✔️] blockdrops-1.12.2-1.4.0
  [✔️] BloodMagic-1.12.2-2.4.1-103
  [✔️] bonsaitrees-1.1.3-b156
  [✔️] Bookshelf-1.12.2-2.3.585
  [✔️] Botania r1.10-361
  [✔️] BrandonsCore-1.12.2-2.4.12.205-universal
  [✔️] brokenwings-2.0.0
  [✔️] BuildingGadgets-2.7.1
  [✔️] capabilityadapter-1.0.1
  [✔️] CarryOn MC1.12.2 v1.12.2
  [✔️] cc-tweaked-1.12.2-1.83.1
  [✔️] Chameleon-1.12-4.1.3
  [✔️] Chisel-MC1.12.2-0.2.1.35
  [✔️] chiselsandbits-14.33
  [✔️] Chunk Pregenerator V1.12-2.1
  [✔️] ClayBucket-1.12-1.1
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.2.353-universal
  [✔️] CoFHCore-1.12.2-4.6.3.27-universal
  [✔️] CoFHWorld-1.12.2-1.3.1.7-universal
  [✔️] colytra-1.12.2-1.2.0
  [✔️] CommonCapabilities-1.12.2-2.4.3
  [✔️] compactmachines3-1.12.2-3.0.18-b278
  [✔️] CompactSolars-1.12.2-5.0.18.341-universal
  [✔️] Controlling-3.0.7
  [✔️] CookingForBlockheads_1.12.2-6.4.71
  [✔️] CosmeticArmorReworked-1.12.2-v4a
  [✔️] CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
  [✔️] CraftTweaker2-1.12-4.1.19
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] CustomBackgrounds-MC1.12-1.1.1
  [✔️] CustomMainMenu-MC1.12.2-2.0.9
  [✔️] Cyclic-1.12.2-1.19.12
  [✔️] CyclopsCore-1.12.2-1.4.0
  [✔️] DarkUtils-1.12.2-1.8.227
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] demagnetize-1.12.2-1.0.1
  [✔️] diethopper-1.1
  [✔️] Ding-1.12.1-1.0.1
  [✔️] dirt2path-1.8.0
  [✔️] DiscordSuite-2.2.4
  [✔️] Draconic-Evolution-1.12.2-2.3.22.343-universal
  [✔️] EmberRootZoo-1.12.2-1.3.10
  [✔️] EnchantingTable-1.12-1.1.3
  [✔️] EnderCore-1.12.2-0.5.73
  [✔️] EnderIO-1.12.2-5.1.55
  [✔️] EnderIO-endergy-1.12.2-5.1.51
  [✔️] EnderStorage-1.12.2-2.4.5.135-universal
  [✔️] engineers_doors-1.12.2-0.8.0
  [✔️] environmentalmaterials-1.12.2-1.0.19.1
  [✔️] environmentaltech-1.12.2-2.0.19.1
  [✔️] Exchangers-1.12.2-2.8
  [✔️] ExCompressum_1.12.2-3.0.27
  [✔️] exnihilocreatio-1.12.2-0.4.5
  [✔️] ExtendedCrafting-1.12.2-1.5.4
  [✔️] ExtraCells-1.12.2-2.6.2a
  [✔️] extrautils2-1.12-1.9.9
  [✔️] ExtremeReactors-1.12.2-0.4.5.50
  [✔️] FarmingForBlockheads_1.12.2-3.1.26
  [✔️] FastFurnace-1.12.2-1.3.1
  [✔️] FastWorkbench-1.12.2-1.7.2
  [✔️] fencejumper-1.12-1.0.5
  [✔️] flatcoloredblocks-mc1.12-6.8
  [✔️] fluxnetworks-1.12.2-3.0.19-21
  [✔️] foamfix-0.10.5-1.12.2
  [✔️] forestry_1.12.2-5.8.2.387
  [✔️] Forgelin-1.8.3
  [✔️] FpsReducer-mc1.12.2-1.12.4
  [✔️] FTBLib-5.4.1.84
  [✔️] FTBUtilities-5.3.0.81
  [✔️] FullscreenWindowed-1.12-1.6.0
  [✔️] GasConduits-1.12.2-1.2.1
  [✔️] gendustry-1.6.5.8-mc1.12.2
  [✔️] gendustryjei-1.0.2
  [✔️] generators-0.9.20.12-mc1.12.2
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] HorseTweaks_1.12.2-1.0.5
  [✔️] HungerPersistence-mc1.12-1.0.1
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] iceandfire-1.7.1-1.12.2
  [✔️] ImmersiveEngineering-0.12-89
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] immersivetech-1.12-1.3.10
  [✔️] incontrol-1.12-3.9.10
  [✔️] industrialcraft-2-2.8.164-ex112
  [✔️] industrialforegoing-1.12.2-1.12.12-236
  [✔️] IntegratedDynamics-1.12.2-1.0.16
  [✔️] IntegratedTunnels-1.12.2-1.6.10
  [✔️] IntegrationForegoing-1.12.2-1.9
  [✔️] InventoryTweaks-1.64+dev.146
  [✔️] IronBackpacks-1.12.2-3.0.8-12
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] JAOPCA-1.12.2-2.2.8.103
  [✔️] jehc-1.12.2-1.6.4
  [✔️] jei_1.12.2-4.15.0.275
  [✔️] jeibees-0.9.0.5-mc1.12.2
  [✔️] jeivillagers-1.12-1.0.2
  [✔️] jepb-1.12-1.2.1
  [✔️] jetif-1.12.2-1.5.1
  [✔️] journeymap-1.12.2-5.5.5b9
  [✔️] JustEnoughEnergistics-1.12.2-1.0.7
  [✔️] JustEnoughPetroleum-0.1
  [✔️] JustEnoughReactors-1.12.2-1.1.1.47
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] JustSleep-1.0.0.1
  [✔️] justthetips-1.12-1.0.1.1
  [✔️] KleeSlabs_1.12.2-5.4.11
  [✔️] LagGoggles-FAT-1.12.2-4.8
  [✔️] LibVulpes-1.12.2-0.4.0-56-universal
  [✔️] limelib-1.12.2-1.7.12
  [✔️] llibrary-1.7.19-1.12.2
  [✔️] lootcapacitortooltips-1.3
  [✔️] LootTableTweaker-1.12.2-1.1.17
  [✔️] LootTweaker-1.12.2-0.0.10
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcjtylib-1.12-3.5.4
  [✔️] MCMultiPart-2.5.3
  [✔️] Mekanism-1.12.2-9.7.9.380
  [✔️] MekanismGenerators-1.12.2-9.7.9.380
  [📁] memory_repo (folder)
  [✔️] MemoryTester-0.4.2
  [✔️] modtweaker-4.0.17
  [✔️] Modular Diversity-1.5
  [✔️] modularmachinery-1.12.2-1.10.0
  [✔️] moreoverlays-1.14-mc1.12.2
  [✔️] Morph-o-Tool-1.2-21
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MTLib-3.0.6
  [✔️] mystagradcompat-1.2
  [✔️] MysticalAgradditions-1.12.2-1.3.2
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] mysticallib-1.12.2-1.3.1
  [✔️] NaturesCompass-1.12.2-1.5.1
  [✔️] Neat 1.4-17
  [✔️] Netherending-Ores-1.12.2-1.3-hotfix1
  [✔️] NoMobSpawningOnTrees-1.2.2-mc1.12.2
  [✔️] NoNVFlash-1.12.2-1.2.0.3-universal
  [✔️] NotEnoughIDs-1.5.4.4
  [✔️] NuclearCraft-2.17a-1.12.2
  [✔️] Nutrition-1.12.2-4.4.0
  [✔️] OldJavaWarning-1.12.2-1.0.10
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenComputers-MC1.12.2-1.7.4.153
  [✔️] OpenModsLib-1.12.2-0.12.2
  [✔️] OreExcavation-1.4.140
  [✔️] overloadedarmorbar-1.0.4g
  [✔️] p455w0rdslib-1.12.2-2.1.44
  [✔️] PackagedAuto-1.12.2-1.0.2.6
  [✔️] Pam's HarvestCraft 1.12.2zd Surprise for Yogcast
  [✔️] Patchouli-1.0-20
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PlaneFix-1.12.2-1.0.0
  [✔️] plethora-1.12.2-1.2.2
  [✔️] plustic-7.1.0.0
  [✔️] PrettyBeaches_1.12.2-1.0.4
  [✔️] ProjectE-1.12.2-PE1.4.1
  [✔️] ProjectIntelligence-1.12.2-1.0.5.21-universal
  [✔️] Psi-r1.1-77
  [✔️] Quark-r1.5-166
  [✔️] questbook-3.1.1-1.12
  [✔️] QuickLeafDecay-MC1.12.1-1.2.4
  [✔️] randompatches-1.12.2-1.17.1.0
  [✔️] RandomThings-MC1.12.2-4.2.7.1
  [✔️] reauth-3.6.0
  [✔️] RebornCore-1.12.2-3.13.12.447-universal
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] RedstoneArsenal-1.12.2-2.6.3.18-universal
  [✔️] RedstoneFlux-1.12-2.1.0.6-universal
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] rftools-1.12-7.72
  [✔️] rftoolsctrl-1.12-2.0.2
  [✔️] rftoolsdim-1.12-5.71
  [✔️] rustic-1.1.0
  [✔️] Scannable-MC1.12.2-1.6.3.24
  [✔️] Schematica-1.12.2-1.8.0.169-universal
  [✔️] simpletrophies-1.2.1
  [✔️] solcarrot-1.12.2-1.8.3
  [✔️] sonarcore-1.12.2-5.0.19-20
  [✔️] StandardExpansion-3.4.159
  [✔️] stg-1.12.2-1.2.3
  [✔️] StorageDrawers-1.12.2-5.3.8
  [✔️] supersoundmuffler-1.12.2-1.0.2.10
  [✔️] TConstruct-1.12.2-2.12.0.157
  [✔️] Tesla-1.12.2-1.0.63
  [✔️] tesla-core-lib-1.12.2-1.0.15
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicComputers-MC1.12.2-0.4.4
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] ThaumicJEI-1.12.2-1.6.0-27
  [✔️] thaumictinkerer-1.12.2-5.0-620a0c5
  [✔️] ThermalCultivation-1.12.2-0.3.3.12-universal
  [✔️] ThermalDynamics-1.12.2-2.5.5.21-universal
  [✔️] ThermalExpansion-1.12.2-5.5.4.43-universal
  [✔️] ThermalFoundation-1.12.2-2.6.3.27-universal
  [✔️] tinker_io-1.12.2-rw2.7.1
  [✔️] TinkersComplement-1.12.2-0.4.2
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] Toast Control-1.12.2-1.8.1
  [✔️] TombManyGraves-1.12-4.2.0
  [✔️] toolprogression-1.12.2-1.6.6
  [✔️] torohealth-1.12.2-11
  [✔️] toughnessbar-2.3
  [✔️] transprot-1.12.2-1.5.3
  [✔️] twilightforest-1.12.2-3.8.689-universal
  [✔️] UniDict-1.12.2-2.9.2
  [✔️] UnlimitedChiselWorks-0.2.2
  [✔️] unloader-1.2.0
  [✔️] valkyrielib-1.12.2-2.0.19.1
  [✔️] villager-market-1.12.2-1.0.1
  [✔️] WailaHarvestability-mc1.12-1.1.12
  [✔️] WanionLib-1.12.2-2.2
  [✔️] Wawla-1.12.2-2.5.273
  [✔️] WirelessCraftingTerminal-1.12.2-3.11.88
  [✔️] WrapUp-1.12-1.1.3
  [✔️] xnet-1.12-1.8.2
  [✔️] YNot-0.2.4
  [✔️] zerocore-1.12-0.1.2.3
```
</details>

**Comment by ace10102** [comment]
did you build the multiblock using botania quartz or thaumic tinkerer quartz
some players on my server have reported the conflict may still be an issue

**Comment by Kiithnaras** [comment]
B-botania smoky quartz...huh...That is certainly...something

**Comment by ace10102** [comment]
thaumic tinkerer's quartz recipe is shapeless while botania's is shaped so they shouldent conflict but its still confusing, neko intended for the enchanter to work with either, and she did some work on this issue a few versions ago so it was either not fully fixed or the fix was somehow reverted

**Comment by Kiithnaras** [comment]
It is very likely an older version of Botania. A cursory bit of research does confirm that, yes, this pack has r1.10.361 and the latest for 1.12.2 is r1.10.363 - which in fact does potentially resolve this very issue:
"Add Quartz blocks to Ore Dictionary (nekosune)"

**Comment by Kiithnaras** [comment]
Using the TC quartz does indeed allow it to enchant as expected, and I'll need to grab that updated file and restart to see if botania quartz works with the updated version. That's crazy, I didn't even notice.

**Comment by nekosune** [comment]
Sorry about this, it seems I didnt fully add in the temporary fix. This is because Vazkii was the original mind behind Thaumic TInkerer, and they took some of their ideas into Botania, as they have the right to do so, including smokey quartz and the recipe

**Comment by Kiithnaras** [comment]
It's all good. The recipes were just a little confusing, what with having accidentally made the Botania quartz by manually making the shaped recipe without realizing instead of doing the shapeless recipe to make the TC black quartz.

I will confirm that the Botania black quartz still causes the issue even with the latest Botania and TT versions for 1.12.2 (r1.10.363 and 5.0 Beta 1.3, respectively), even though the TT black quartz is allows the enchanter to work perfectly fine.

**Comment by nekosune** [comment]
Will try and fix this in next beta

**Comment by xJon** [comment]
Was this fix ever released? Would be very useful :)

**Comment by aimeesunflower** [comment]
> Was this fix ever released? Would be very useful :)
@xJon 

The fix has been incorporated into the code, but as far as I understand, at this point in time, it's not yet in the CF version, pending other updates. Will leave @KatrinaAS to give a more precise update for you.
