### ISSUE TITLE
ummm.. halp?

### ISSUE THREAD

**Issue by TheSlimeMan** [Thaumic-Tinkerer/ThaumicTinkerer#617]
This happened.

------------------------------

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/1/15 11:30 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: enchPotency
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: enchPotency
	at thaumic.tinkerer.common.enchantment.core.EnchantmentManager.initEnchantmentData(EnchantmentManager.java:72)
	at thaumic.tinkerer.common.core.proxy.TTCommonProxy.init(TTCommonProxy.java:81)
	at thaumic.tinkerer.client.core.proxy.TTClientProxy.init(TTClientProxy.java:81)
	at thaumic.tinkerer.common.ThaumicTinkerer.init(ThaumicTinkerer.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 251817080 bytes (240 MB) / 534691840 bytes (509 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 52 mods loaded, 52 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.2.1277} [Minecraft Forge] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Thaumcraft{4.2.2.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	arsmagica2{1.4.0.005} [Ars Magica 2] (1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	hearts{1.0} [Hearts] ([1.7.10][1.7.2] Heart Crystal 1.0 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized
	AnimationAPI{1.2.3} [AnimationAPI] (AnimationAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized
	be{2.0} [Bedrockium Mod] (Bedrockium-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	AWWayofTime{v1.2.0Beta24} [Blood Magic: Alchemical Wizardry] (Blood Magic-v1.2.0Beta24(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized
	craftingpillars{1.6} [CraftingPillars Mod] (CraftingPillars-1.7.2-1.6 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	DeadlyWorld{1.0.2} [Deadly World] (Deadly-World-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	tlhpoeCore{1.7} [TLHPoE Core] (TLHPoE-Core-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	enderrepositories{1.4} [Ender Repositories] (Ender-Repositories-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	extracells{2.1.11} [ExtraCells] (ExtraCells-2.1.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ThaumicTinkerer{2.5-1.7.10-153} [Thaumic Tinkerer] (Thaumic-Tinkerer-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Errored
	ForbiddenMagic{1.7.10-0.51} [Forbidden Magic] (Forbidden-Magic-Mod-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized
	tnb_gildedarmor{1.1} [TNB Gilded Armor] (Gilded-Armor-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	tnbcraftingrecipes{1.0} [TNB Useful Crafting Recipes] (Gilded-Armor-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	journeymap{4.0.1} [JourneyMap] (JourneyMap-Mod-1.7.10-Unlimited.jar) Unloaded->Constructed->Pre-initialized->Initialized
	lycanitesmobs{1.10.4.4 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	arcticmobs{1.10.4.4 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	demonmobs{1.10.4.4 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	desertmobs{1.10.4.4 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	forestmobs{1.10.4.4 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	freshwatermobs{1.10.4.4 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	infernomobs{1.10.4.4 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	junglemobs{1.10.4.4 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	mountainmobs{1.10.4.4 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	plainsmobs{1.10.4.4 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	saltwatermobs{1.10.4.4 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	shadowmobs{1.10.4.4 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	swampmobs{1.10.4.4 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (Magical-Crops-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10 (4).jar) Unloaded->Constructed->Pre-initialized->Initialized
	me{1.0.1} [More Enchantments] (More-Enchantments-Mod-1.7.10 (4).jar) Unloaded->Constructed->Pre-initialized->Initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NodalMechanics{1.7.10R1.0} [NodalMechanics] (Nodal-Mechanics-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	primitivemobs{1.0} [Primitive Mobs] (Primitive-Mobs-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjectE{1.7.10-0.2d-dev12} [ProjectE] (ProjectE-1.7.10-0.2d-dev12.jar) Unloaded->Constructed->Pre-initialized->Initialized
	RandomThings{2.1.7} [Random Things] (RandomThings-2.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Sanguimancy{1.1.8} [Sanguimancy] (Sanguimancy-1.7.10-1.1.8-4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	thaumicenergistics{0.8.7.2b-rv1} [Thaumic Energistics] (Thaumic-Energistics-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ThaumicMachina{1.7.10-0.1.0 (Open-Beta)} [Thaumic Machina] (Thaumic-Machina-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	RioVII{v1.0.1} [The Mists of RioV II - Shadow of Aun'Tun] (The-Mists-of-RioV-II-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187

**Comment by nekosune** [comment]
Please update to latest version.

**Comment by snaper6010** [comment]
I AM on the latest version. thaumcraft 4.2.3.4

**Comment by nekosune** [comment]
You need the latest Thaumic Tinkerer of which you do not have

**Comment by nekosune** [comment]
And at the time of the error.  You had Thaumcraft 4.4.2.1 not 4.2.3.4 accurate information is needed
