### ISSUE TITLE
Crash client without Computer Craft installed With Build #466

### ISSUE THREAD

**Issue by prodkid** [Thaumic-Tinkerer/ThaumicTinkerer#663]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/8/15 6:12 AM
Description: Initializing game

java.lang.NoClassDefFoundError: dan200/computercraft/api/turtle/ITurtleUpgrade
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.api.turtle.ITurtleUpgrade
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 269348208 bytes (256 MB) / 518062080 bytes (494 MB) up to 17110138880 bytes (16317 MB)
	Mod Pack: ~~ERROR~~ NullPointerException: null
	LiteLoader Mods: ~~ERROR~~ NullPointerException: null
	LaunchWrapper: 44 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ModelBipedTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemRendererTransformer
          - Transformer: mods.battlegear2.coremod.transformers.MinecraftTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemStackTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemInWorldTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: openeye.asm.MultiTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: mods.battlegear2.coremod.transformers.BattlegearAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreAccessTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreTransformer
          - Transformer: ivorius.psychedelicraftcore.PsychedelicraftClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16384m -Xincgc -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 77 mods loaded, 77 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	ivtoolkit{1.0.2} [IvToolkit] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems.jar) Unloaded->Constructed
	OpenEye{0.6} [OpenEye] (OpenEye.jar) Unloaded->Constructed
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (MalisisCore.jar) Unloaded->Constructed
	psychedelicraftcore{1.4} [Psychedelicraft Core] (minecraft.jar) Unloaded->Constructed
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI.jar) Unloaded->Constructed
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips.jar) Unloaded->Constructed
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
	ArmorStatusHUD{1.27} [ArmorStatusHUD] (ArmorStatusHUD.jar) Unloaded->Constructed
	arsmagica2{1.4.0.005} [Ars Magica 2] (ArsMagica2.jar) Unloaded->Constructed
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (BattleGear2.jar) Unloaded->Constructed
	BattleTowers{1.4.9} [Battle Towers] (BattleTowers.jar) Unloaded->Constructed
	betterrecords{1.7.10-1.1.9} [Better Records] (betterrecords.jar) Unloaded->Constructed
	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen.jar) Unloaded->Constructed
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft.jar) Unloaded->Constructed
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty.jar) Unloaded->Constructed
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoodsBiomesOPlenty.jar) Unloaded->Constructed
	AWWayofTime{v1.3.0b} [Blood Magic: Alchemical Wizardry] (BloodMagic.jar) Unloaded->Constructed
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft.jar) Unloaded->Constructed
	Botania{r1.4-156} [Botania] (Botania.jar) Unloaded->Constructed
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (CarpentersBlocks.jar) Unloaded->Constructed
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest.jar) Unloaded->Constructed
	chisel{2.3.5.31} [Chisel 2] (Chisel.jar) Unloaded->Constructed
	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft.jar) Unloaded->Constructed
	customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs.jar) Unloaded->Constructed
	DamageIndicatorsMod{3.2.3} [Damage Indicators] (DamageIndicatorsMod.jar) Unloaded->Constructed
	props{1.11} [Decocraft] (Decocraft.jar) Unloaded->Constructed
	dungeonpack{1.7.10-1.0} [Dungeon Pack] (dungeonpack.jar) Unloaded->Constructed
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus.jar) Unloaded->Constructed
	fairylights{0.6} [Fairy Lights] (FairyLights.jar) Unloaded->Constructed
	fairymod{0.5} [Fairy Mod] (FairyMod.jar) Unloaded->Constructed
	farlanders{1.2b} [The Farlanders] (farlanders.jar) Unloaded->Constructed
	Steamcraft{0.27.4} [Flaxbeard's Steam Power] (FlaxbeardsSteamPower.jar) Unloaded->Constructed
	Waila{1.5.8} [Waila] (Waila.jar) Unloaded->Constructed
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer.jar) Unloaded
	ForbiddenMagic{1.7.10-0.552} [Forbidden Magic] (ForbiddenMagic.jar) Unloaded
	GraveStone{2.11.3} [GraveStone] (GraveStone.jar) Unloaded
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil.jar) Unloaded
	Hats{4.0.1} [Hats] (Hats.jar) Unloaded
	InfernalMobs{1.5.7} [Infernal Mobs] (InfernalMobs.jar) Unloaded
	JABBA{1.2.0a} [JABBA] (Jabba.jar) Unloaded
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (MalisisDoors.jar) Unloaded
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle.jar) Unloaded
	mod_MedievalWars{0.1} [Medievalwars] (Medievalwars.jar) Unloaded
	radixcore{1.3.4} [RadixCore] (RadixCore.jar) Unloaded
	mca{4.1.5} [Minecraft Comes Alive] (MinecraftComesAlive.jar) Unloaded
	AS_Minions{1.9.4} [Minions] (Minions.jar) Unloaded
	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels.jar) Unloaded
	necromancy{1.7.0} [Necromancy] (Necromancy.jar) Unloaded
	NEIAddons{1.12.3.11} [NEI Addons] (NEIAddons.jar) Unloaded
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (NEIAddons.jar) Unloaded
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (NEIAddons.jar) Unloaded
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (NEIAddons.jar) Unloaded
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (NEIAddons.jar) Unloaded
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (PamsHarvestCraft.jar) Unloaded
	ProjectE{1.7.10-PE1.1.0} [ProjectE] (ProjectE.jar) Unloaded
	ProjectZulu|Core{1.7.10-1.4b4} [Project Zulu] (ProjectZulu.jar) Unloaded
	psychedelicraft{1.5.1.1} [Psychedelicraft] (Psychedelicraft.jar) Unloaded
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike.jar) Unloaded
	AS_Ruins{13.8} [Ruins Spawning System] (Ruins.jar) Unloaded
	secretroomsmod{4.7.1} [The SecretRoomsMod] (SecretRoomsMod.jar) Unloaded
	StatusEffectHUD{1.26} [StatusEffectHUD] (StatusEffectHUD.jar) Unloaded
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct.jar) Unloaded
	thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin] (ThaumcraftNEIPlugin.jar) Unloaded
	erebus{0.2pre12} [Erebus] (TheErebus.jar) Unloaded
	Trapcraft{v2.2.1a} [Trapcraft] (Trapcraft.zip) Unloaded
	Treecapitator{1.7.10} [Treecapitator] (Treecapitator.jar) Unloaded
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability.jar) Unloaded
	wawla{1.1.1} [What Are We Looking At] (Wawla.jar) Unloaded
	witchery{0.21.2} [Witchery] (witchery.jar) Unloaded
	yegamolchattels{1.1.1.1} [Ye Gamol Chattels] (YeGamolChattels.jar) Unloaded
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: ASUS R9 280X Series GL version 4.3.12618 Compatibility Profile Context 13.251.0.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by nekosune** [comment]
Can you give me a fine level log please
