### ISSUE TITLE
random Crash

### ISSUE THREAD

**Issue by crunkazcanbe** [Thaumic-Tinkerer/ThaumicTinkerer#685]
Description: Exception in server tick loop

java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:651)
	at net.minecraft.client.renderer.texture.TextureUtil.func_94277_a(SourceFile:379)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(SourceFile:43)
	at thaumcraft.client.lib.TCFontRenderer.<init>(TCFontRenderer.java:117)
	at thaumcraft.client.gui.GuiResearchRecipe.<init>(GuiResearchRecipe.java:180)
	at thaumic.tinkerer.client.gui.GuiResearchPeripheral.<init>(GuiResearchPeripheral.java:30)
	at thaumic.tinkerer.client.core.handler.ClientTickHandler.tickEnd(ClientTickHandler.java:39)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1054_ClientTickHandler_tickEnd_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by nekosune** [comment]
This has been fixed in latest at http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/
This will be in curseforge in a week or so
