### ISSUE TITLE
Crash+Server corrupt with osmotic enchanter (TT 162, TC 4.2.3.4)

### ISSUE THREAD

**Issue by zabi94** [Thaumic-Tinkerer/ThaumicTinkerer#693]
Whenever i try to enchant something, the instant i press the button inside the enchanter, the world corrupts, and i have to use mcedit to delete the block. I tried twice to be sure it wasn't due to metallurgy stuff i was trying to enchant, but it crashes even with vanilla enchantable items...

```
---- Minecraft Crash Report ----
// Oops.

Time: 17/03/15 14.42
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322)
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305)
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322)
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305)
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159)

-- Block entity being ticked --
Details:
	Name: ttinkerer:enchanter // thaumic.tinkerer.common.block.tile.TileEnchanter
	Block type: ID #1214 (tile.enchanter // thaumic.tinkerer.common.block.BlockEnchanter)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-36,79,147), Chunk: (at 12,4,3 in -3,9; contains blocks -48,0,144 to -33,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1214 (tile.enchanter // thaumic.tinkerer.common.block.BlockEnchanter)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['zabi94'/249, l='MpServer', x=-33,33, y=80,62, z=147,22]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (2,64,-81), Chunk: (at 2,4,15 in 0,-6; contains blocks 0,0,-96 to 15,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 16824786 game time, 17836960 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 78 total; [EntitySquid['Squid'/8960, l='MpServer', x=-75,50, y=60,28, z=153,81], EntityZombie['Zombie'/7681, l='MpServer', x=22,50, y=34,00, z=185,69], EntitySquid['Squid'/8961, l='MpServer', x=-74,47, y=60,00, z=156,47], EntityGolemBase['Straw Golem'/131, l='MpServer', x=-27,22, y=75,00, z=135,78], EntityVillager['Villager'/132, l='MpServer', x=-32,22, y=75,00, z=134,50], EntityZombie['Zombie'/7684, l='MpServer', x=18,50, y=34,00, z=180,31], EntityBat['Bat'/9092, l='MpServer', x=27,75, y=33,00, z=177,25], EntityVillager['Villager'/133, l='MpServer', x=-27,47, y=75,00, z=134,75], EntityZombie['Zombie'/7685, l='MpServer', x=19,50, y=34,00, z=182,50], EntityGolemBase['Wood Golem'/134, l='MpServer', x=-32,78, y=75,88, z=135,78], EntityCreeper['Creeper'/7686, l='MpServer', x=23,69, y=34,00, z=180,78], EntityZombie['Zombie'/135, l='MpServer', x=-19,06, y=70,00, z=161,50], EntitySkeleton['Skeleton'/6791, l='MpServer', x=-32,66, y=37,00, z=116,09], EntitySkeleton['Skeleton'/8584, l='MpServer', x=25,09, y=60,00, z=88,91], EntityCreeper['Creeper'/8585, l='MpServer', x=28,50, y=60,00, z=89,50], EntityCreeper['Creeper'/8586, l='MpServer', x=25,50, y=60,00, z=90,50], EntityEnderman['Enderman'/8843, l='MpServer', x=-66,97, y=28,00, z=133,41], EntityCreeper['Creeper'/9100, l='MpServer', x=-58,50, y=22,00, z=127,50], EntityCreeper['Creeper'/9101, l='MpServer', x=-59,50, y=22,00, z=127,50], EntityClientPlayerMP['zabi94'/249, l='MpServer', x=-33,33, y=80,62, z=147,22], EntitySkeleton['Skeleton'/8847, l='MpServer', x=29,50, y=61,00, z=91,50], EntityCreeper['Creeper'/8080, l='MpServer', x=-103,94, y=12,00, z=96,66], EntityBat['Bat'/8208, l='MpServer', x=-97,31, y=61,10, z=97,69], EntityWitch['Witch'/8595, l='MpServer', x=-50,50, y=23,00, z=122,50], EntityBat['Bat'/5780, l='MpServer', x=37,25, y=22,10, z=77,25], EntityZombie['Zombie'/8596, l='MpServer', x=-48,50, y=23,00, z=123,50], EntitySkeleton['Skeleton'/8599, l='MpServer', x=-46,56, y=23,00, z=123,44], EntityZombie['Zombie'/7576, l='MpServer', x=32,50, y=61,00, z=93,50], EntitySkeleton['Skeleton'/8600, l='MpServer', x=-47,91, y=23,00, z=125,50], EntityTrail['unknown'/410, l='MpServer', x=-33,33, y=80,62, z=147,22], EntitySkeleton['Skeleton'/9254, l='MpServer', x=-1,50, y=60,00, z=75,50], EntityCreeper['Creeper'/7975, l='MpServer', x=-64,50, y=25,00, z=125,50], EntityZombie['Zombie'/9255, l='MpServer', x=-12,47, y=60,00, z=80,47], EntityBat['Bat'/6954, l='MpServer', x=-65,41, y=60,99, z=106,66], EntityBat['Bat'/9002, l='MpServer', x=5,50, y=34,26, z=190,11], EntityBat['Bat'/6955, l='MpServer', x=-48,84, y=59,00, z=121,03], EntitySpider['Spider'/9389, l='MpServer', x=3,50, y=39,00, z=191,50], EntitySpider['Spider'/9390, l='MpServer', x=5,50, y=39,00, z=191,50], EntityCreeper['Creeper'/6321, l='MpServer', x=15,50, y=12,00, z=158,50], EntityCreeper['Creeper'/6965, l='MpServer', x=-46,50, y=23,00, z=120,50], EntitySkeleton['Skeleton'/5559, l='MpServer', x=34,41, y=19,00, z=85,34], EntitySkeleton['Skeleton'/5561, l='MpServer', x=43,50, y=19,00, z=78,50], EntityWitch['Witch'/7865, l='MpServer', x=30,50, y=46,00, z=144,50], BlueSlime['Blue Slime'/319, l='MpServer', x=-84,69, y=144,00, z=159,22], BlueSlime['Blue Slime'/320, l='MpServer', x=-85,78, y=144,00, z=154,29], EntityItem['item.item.tconstruct.strangefood.edibleslime'/2884, l='MpServer', x=-80,03, y=144,13, z=161,19], EntitySkeleton['Skeleton'/8011, l='MpServer', x=-71,50, y=18,00, z=103,50], EntitySkeleton['Skeleton'/7374, l='MpServer', x=-43,50, y=18,00, z=131,50], EntityBat['Bat'/8654, l='MpServer', x=-106,69, y=45,10, z=210,69], EntityZombie['Zombie'/8910, l='MpServer', x=-43,50, y=12,00, z=154,50], EntitySpider['Spider'/2639, l='MpServer', x=46,50, y=-1120,07, z=12,09], EntitySkeleton['Skeleton'/7375, l='MpServer', x=-44,50, y=18,00, z=130,50], EntityBat['Bat'/8656, l='MpServer', x=-106,90, y=39,16, z=212,23], EntitySkeleton['Skeleton'/8912, l='MpServer', x=-42,50, y=12,00, z=150,50], EntitySpider['Spider'/9424, l='MpServer', x=-70,50, y=17,00, z=122,50], EntitySkeleton['Skeleton'/8913, l='MpServer', x=-41,50, y=12,00, z=152,50], EntitySpider['Spider'/9425, l='MpServer', x=-70,50, y=17,00, z=120,50], EntityPig['Pig'/338, l='MpServer', x=14,84, y=79,00, z=200,13], EntitySpider['Spider'/8404, l='MpServer', x=-62,22, y=17,00, z=104,19], EntitySkeleton['Skeleton'/8405, l='MpServer', x=-66,50, y=16,00, z=103,50], EntityBat['Bat'/8789, l='MpServer', x=7,60, y=37,30, z=70,75], EntityItem['item.item.bone'/2518, l='MpServer', x=-49,84, y=78,13, z=209,03], EntityPig['Pig'/351, l='MpServer', x=21,63, y=77,00, z=198,06], EntitySkeleton['Skeleton'/7648, l='MpServer', x=1,09, y=60,00, z=78,50], EntityBat['Bat'/9313, l='MpServer', x=-107,39, y=46,19, z=186,35], EntityBat['Bat'/9061, l='MpServer', x=35,57, y=21,29, z=75,38], EntityZombie['Zombie'/5095, l='MpServer', x=-12,50, y=34,00, z=124,50], EntityCreeper['Creeper'/8936, l='MpServer', x=-34,50, y=39,00, z=126,50], EntityCreeper['Creeper'/7018, l='MpServer', x=-67,34, y=64,00, z=93,34], EntityZombie['Zombie'/8810, l='MpServer', x=-103,50, y=41,00, z=208,50], EntityBat['Bat'/7917, l='MpServer', x=31,50, y=61,45, z=87,47], EntityBat['Bat'/9326, l='MpServer', x=43,88, y=11,07, z=183,31], EntityItem['item.item.tconstruct.strangefood.edibleslime'/3824, l='MpServer', x=-89,88, y=143,13, z=161,88], EntitySkeleton['Skeleton'/6259, l='MpServer', x=43,50, y=25,00, z=68,50], EntityWitch['Witch'/6517, l='MpServer', x=-106,50, y=38,00, z=213,50], EntityBat['Bat'/8187, l='MpServer', x=6,80, y=59,10, z=90,61], EntityItem['item.item.tconstruct.strangefood.edibleslime'/2556, l='MpServer', x=-79,88, y=142,13, z=162,56], EntityCreeper['Creeper'/9215, l='MpServer', x=-79,50, y=60,00, z=111,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 799935472 bytes (762 MB) / 2105540608 bytes (2008 MB) up to 2105540608 bytes (2008 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 63 mods loaded, 63 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems1.0.4.83.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	VeinMiner_coremod{null_build-null} [Core mod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics201.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraftv1.9.2MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty2.1.0.1067.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore3.0.0RC7-211.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0RC7} [Thermal Foundation] (ThermalFoundation1.0.0RC7-62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0RC7} [Thermal Expansion] (ThermalExpansion4.0.0RC7-141.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BigReactors{0.4.2A2} [Big Reactors] (BigReactors0.4.2A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic1.3.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.3.6} [BuildCraft] (buildcraft6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.3.6} [BC Transport] (buildcraft6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.3.6} [BC Silicon] (buildcraft6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.3.6} [BC Builders] (buildcraft6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.3.6} [BC Energy] (buildcraft6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.3.6} [BC Factory] (buildcraft6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (CarpentersBlocks3.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft4.2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TwilightForest{2.3.4} [The Twilight Forest] (twilightforest2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chisel{2.3.7.34} [Chisel 2] (Chisel2.3.7.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO2.2.8.349.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Waila{1.5.8} [Waila] (Waila1.5.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy4.0.8.97.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FastCraft{1.9} [FastCraft] (fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	funkylocomotion{1.0} [Funky Locomotion] (funkylocomotion5a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	JABBA{1.2.0b} [JABBA] (Jabba1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	metaskin{0.0.1} [MetaSkin] (metaskin-0.0.2-ubuntuCompiled.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Morph{0.9.1} [Morph] (Morph0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MultiWorld{1.2.7} [Multi World] (Multiworld1.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	tcnodetracker{1.0.4} [TC Node Tracker] (tcnodetracker-1.7.10-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	thaumicenergistics{0.8.9.0b-rv2} [Thaumic Energistics] (thaumicenergistics0.8.9.0brv2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer2.5.162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration1.1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicHorizons{1.0} [Thaumic Horizons] (thaumichorizons1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics] (ThermalDynamics1.0.0RC7-98.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	VeinMiner{0.21.0} [Vein Miner] (VeinMiner-1.7.10_0.21.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	VeinMinerModSupport{0.21.0} [Mod Support] (VeinMiner-1.7.10_0.21.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	CoFHCore: -[1.7.10]3.0.0RC7-211
	ThermalFoundation: -[1.7.10]1.0.0RC7-62
	ThermalExpansion: -[1.7.10]4.0.0RC7-141
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.0.0RC7-98
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4061, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [metaskin.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by nekosune** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/
If you use the latest there it will work, and the world will work
(it dosnt corrupt, it just makes the world not work until working version is loaded)

**Comment by zabi94** [comment]
Oh, ok, I thought that 162 was the last version available, my bad

**Comment by nekosune** [comment]
No trouble, the curse will be updated soon, its just more thigns keep popping up
