### ISSUE TITLE
Osmotic table enchantment

### ISSUE THREAD

**Issue by BlesseNtumble** [Thaumic-Tinkerer/ThaumicTinkerer#710]
When you try to enchant the table game crash. 
And on the server simply disappears table together with the object and wand

[18:48:48] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322) ~[ItemWandCasting.class:?]
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305) ~[ItemWandCasting.class:?]
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159) ~[TileEnchanter.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more
[18:48:48] [Server thread/ERROR]: This crash report has been saved to: Minecraft1.7.10\crash-reports\crash-2015-03-30_18.48.48-server.txt
[18:48:48] [Server thread/INFO]: Stopping server
[18:48:48] [Server thread/INFO]: Saving players
[18:48:48] [Server thread/INFO]: Saving worlds
[18:48:48] [Server thread/INFO]: Saving chunks for level 'Новый мир'/Overworld
[18:48:48] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 30.03.15 18:48
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322)
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305)
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Brycey92** [comment]
What version of TC and TT are you using?

**Comment by nekosune** [comment]
Fixed allready in latest.

**Comment by nekosune** [comment]
Also you have removeTileEntity on error set to true in forge.cfg that is a bad idea because whenever a tile entity errors, the block wil be removed, whether it was a one off error or not

**Comment by Brycey92** [comment]
@BlesseNtumble, the latest dev builds can be found here: http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/
