### ISSUE TITLE
Crash after using osmotic enchanter

### ISSUE THREAD

**Issue by exodawn** [Thaumic-Tinkerer/ThaumicTinkerer#712]
I have had this problem twice now. after i tried to use the osmotic enchanter the server crash and becaomes unavaible to connect to. The items that i tried to enchant were: the thamethuges void robes and simpely jet packs dark plate.i wonder if this is a known issue. i hope you guys can test and check this out.

**Comment by Brycey92** [comment]
What version of TC and TT are you using? Also, can we get a crash report?

**Comment by TTFTCUTS** [comment]
Same error. Was attempting to enchant a thaumium grafter with repair 2, using a manasteel-capped livingwood sceptre.

Relevant part of the report:

```
java.lang.NullPointerException: Ticking block entity
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322)
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305)
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by nekosune** [comment]
>.< I really need to get this update out, I just keep finding more to fix, 
go to 
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

This was fixed a while ago
