### ISSUE TITLE
Thaumonomicon Crash on Thaumic Tinkerer Section

### ISSUE THREAD

**Issue by jonnyowenpowell** [Thaumic-Tinkerer/ThaumicTinkerer#718]
When the Thaumic Tinkerer section of the Thaumonomicon is navigated to, in FTB Infinity, after around a second, even if no icon is clicked, the game crashes. Here is the exception:
`java.lang.RuntimeException: No OpenGL context found in the current thread.`
And here is the relevant part of the stack trace, wrapped with one non Thaumcraft/Thaumic Tinkerer class on either side to show context:

``` java
at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(SourceFile:43)
at thaumcraft.client.lib.TCFontRenderer.<init>(TCFontRenderer.java:117)
at thaumcraft.client.gui.GuiResearchRecipe.<init>(GuiResearchRecipe.java:180)
at thaumic.tinkerer.client.gui.GuiResearchPeripheral.<init>(GuiResearchPeripheral.java:30)
at thaumic.tinkerer.client.core.handler.ClientTickHandler.tickEnd(ClientTickHandler.java:39)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_778_ClientTickHandler_tickEnd_TickEvent.invoke(.dynamic)
```

EDIT - 
I am aware of issue #593 and the duplicates/related issues, but I am running on the latest build (filename: ThaumicTinkerer-2.5-1.7.10-481) and the crash still occurs.

EDIT 2 -
It has occurred to me there is a small chance it may be relevant that I am playing SSP, not SMP. I currently don't have access to an SMP server to test if I get the issue there, apologies.

**Comment by nekosune** [comment]
I need full log please not 'context'

**Comment by jonnyowenpowell** [comment]
Hey sorry I didn't mean to offend with that! Anyway, it's the exact same stack trace as in #593.

**Comment by nekosune** [comment]
Will look into this, it is a hard one to fix as I can not reproduce it

**Comment by jonnyowenpowell** [comment]
Thanks! I am running FTB Infinity 1.4.0 on Java 1.7, in case that's useful for reproducing it.

**Comment by jonnyowenpowell** [comment]
I know that's not a development environment, but the more info the better right :)
