### ISSUE TITLE
random tileinfusedgrain crash

### ISSUE THREAD

**Issue by shadoxxhd** [Thaumic-Tinkerer/ThaumicTinkerer#733]
happened 3 times, always around 20-30s after loading a level, but only in one of four cases (world is playable, infused seeds grow without problems)

java.lang.NullPointerException: Ticking block entity
    at thaumic.tinkerer.common.block.tile.TileInfusedGrain.func_145845_h(TileInfusedGrain.java:50)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Details:
    Name: ttinkerer:infusedGrainBlock // thaumic.tinkerer.common.block.tile.TileInfusedGrain
    Block type: ID #1617 (tile.infusedGrainBlock // thaumic.tinkerer.common.block.BlockInfusedGrain)
    Block data value: 7 / 0x7 / 0b0111
    Block location: World: (35,69,246), Chunk: (at 3,4,6 in 2,15; contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #1617 (tile.infusedGrainBlock // thaumic.tinkerer.common.block.BlockInfusedGrain)
    Actual block data value: 7 / 0x7 / 0b0111

if you need additional info, i have a backup of the log file

**Comment by katzenpapst** [comment]
I think this is the same bug that I just came here to report: infused grains sometimes crash the client on harvest. It reproducibly happens to me with volatus plants, and also happened with an Ira (from ForbiddenMagic) plant. While it kinda makes sense for mod aspects, why volatus?

I'll post the log when I get home

**Comment by Ghostlyr** [comment]
I have simmilar issue with 510 thaumic tinkerer build. Near with my spawn location have been planted infused seeds, but when i break it,i got a seeds without any NBT data...

![image](https://cloud.githubusercontent.com/assets/8511068/10428475/8ab273de-7113-11e5-86e8-905371f2e56c.png)
