### ISSUE TITLE
Getting kicked when using Auto Smelt on Dense Ores

### ISSUE THREAD

**Issue by antisocialian** [Thaumic-Tinkerer/ThaumicTinkerer#780]
I have tested this with different pickaxes(modded and vanilla) and it happens the same I mine a dense ore with auto-smelt and I get kicked with an Internal Server Error. The server log shows this:

```
[13:03:10] [Server thread/WARN]: Failed to handle packet for /192.168.1.134:53182
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_45]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_45]
	at tterrag.core.common.handlers.AutoSmeltHandler.handleBlockBreak(AutoSmeltHandler.java:34) ~[AutoSmeltHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_778_AutoSmeltHandler_handleBlockBreak_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:155) ~[ForgeEventFactory.class:?]
	at com.rwtema.denseores.BlockDenseOre.func_149690_a(BlockDenseOre.java:241) ~[BlockDenseOre.class:?]
	at net.minecraft.block.Block.func_149697_b(Block.java:648) ~[aji.class:?]
	at net.minecraft.block.Block.func_149636_a(Block.java:974) ~[aji.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:299) ~[mx.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498) ~[nh.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[13:03:10] [Server thread/INFO]: antisocialian lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[13:03:10] [Server thread/INFO]: antisocialian left the game
```

I haven't posted this to RWTema for the Dense Ores yet, as it listed the Thaumic Tinkerer first in the error.

**Comment by nekosune** [comment]
Thaumic tinkerer is nowhere in that error, if you mean tterrag.core.common.handlers.AutoSmeltHandler thats https://github.com/tterrag1098/ttCore

**Comment by antisocialian** [comment]
:( sry
