### ISSUE TITLE
Crashing On Startup

### ISSUE THREAD

**Issue by LordOfSouls95** [Thaumic-Tinkerer/ThaumicTinkerer#815]
Hi there, installed the latest version of Thaumic Tinkerer (update dated Nov27th) and now Minecraft crashes when trying to load up my modded version. Here is the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8-5.0.3.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 12/12/15 22:13
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:538)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.ILanguageAdapter$ScalaAdapter.setInternalProxies(ILanguageAdapter.java:140)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:82)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
	... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.lib.packet.PacketCustom$ICustomPacketHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 136306064 bytes (129 MB) / 287903744 bytes (274 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UC	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UC	Baubles{1.1.1.0} [Baubles] (Baubles-1.8-1.1.1.0.jar) 
	UC	Thaumcraft{5.0.3} [Thaumcraft] (Thaumcraft-1.8-5.0.3.jar) 
	UE	thaumictinkerer{${version}} [Thaumic Tinkerer] (ThaumicTinkerer-3.0-1.8-168.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8-5.0.3.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3574' Renderer: 'Intel(R) HD Graphics 4400'

**Comment by nekosune** [comment]
As stated on curse it depends on code chicken lib,  or code chicken core.
Will update this week to make that clear.

**Comment by LordOfSouls95** [comment]
I have CCC installed correctly yet it's still giving me the same error.

**Comment by LordOfSouls95** [comment]
Thanks, I've got it all working now. I appreciate the help.

**Comment by Peach774** [comment]
This issue is occuring for me in 1.8.9 which has no version of code chicken core.

**Comment by nekosune** [comment]
@Peach774 download the 1.8.1 Code Chicken LIB not core

**Comment by Peach774** [comment]
Where do i find that? And it will work with 1.8.9?

**Comment by nekosune** [comment]
http://files.minecraftforge.net/CodeChickenLib/ and yes, it will, tested to work.

**Comment by Peach774** [comment]
Thanks

**Comment by WolfBV** [comment]
https://www.curseforge.com/minecraft/mc-mods/codechickenlib-1-8-9
