### ISSUE TITLE
1.7.10 if I hit right click with empty hand on terra seed i get crash

### ISSUE THREAD

**Issue by adamsonich** [Thaumic-Tinkerer/ThaumicTinkerer#843]
http://pastebin.com/9Bv4F9JM
using ThaumicTinkerer-2.5-1.7.10-523.jar
518 version ticking out our server

**Comment by adamsonich** [comment]
if left click with empty/not empty hand i get disconnect from server and on server side
`java.lang.NullPointerException   
        at thaumic.tinkerer.common.block.BlockInfusedGrain.getDrops(BlockInfusedGrain.java:132) ~[BlockInfusedGrain.class:?]                                                                         
        at net.minecraft.block.Block.func_149690_a(Block.java:655) ~[aji.class:?]                                                                                                                    
        at net.minecraft.block.BlockCrops.func_149690_a(BlockCrops.java:149) ~[akf.class:?]                                                                                                          
        at net.minecraft.block.Block.func_149697_b(Block.java:648) ~[aji.class:?]                                                                                                                    
        at net.minecraft.block.Block.func_149636_a(Block.java:974) ~[aji.class:?]                                                                                                                    
        at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:299) ~[mx.class:?]                                                                                
        at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:186) ~[mx.class:?]                                                                                
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489) ~[nh.class:?]                                                                                     
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]                                                                                       
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]                                                                                        
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]                                                                                                  
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]                                                                                                    
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]                                                                                     
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]                                                                                        
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]                                                                                     
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]                                                                                              
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]        `

**Comment by adamsonich** [comment]
mmm, which "branch" needed to set for correct version of 1.7.10?

**Comment by adamsonich** [comment]
ok, on right click problem:
https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/commit/f3a167dc8a0e76a8c05c8a9db978f34a558f161b?diff=split#diff-1bfb5d3d8a31911c21b80c393af0e4d5R33
which version of Thaumcraft needed?

**Comment by Dream-Master** [comment]
Have the same crash here.

**Comment by Dream-Master** [comment]
When the seed is mature i get this crash.

https://gist.github.com/Dream-Master/6863c41ca34caa9962df#file-tt2

**Comment by adamsonich** [comment]
No. The only solution is roll back to version 2.5-1.7.10-512

**Comment by nekosune** [comment]
@Dream-Master  please make new issues for different errors. do not piggyback others
