### ISSUE TITLE
Server crashes upon usage of foci

### ISSUE THREAD

**Issue by Mstrodl** [Thaumic-Tinkerer/ThaumicTinkerer#858]
When I use foci, the server crashes with the following error:

> [20:37:16] [Server thread/WARN]: java.lang.NoSuchMethodException: thaumic.tinkerer.common.item.kami.foci.ItemFocusShadowbeam$Beam.<init>(net.minecraft.world.World)
[20:37:16] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[20:37:16] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Class.java:1825)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.EntityList.func_75620_a(EntityList.java:122)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.Entity.teleportTo(Entity.java:2513)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.Entity.func_71027_c(Entity.java:2489)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.Entity.func_70030_z(Entity.java:454)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:409)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:128)
[20:37:16] [Server thread/WARN]: 	at thaumic.tinkerer.common.item.kami.foci.ItemFocusShadowbeam$Beam.func_70071_h_(ItemFocusShadowbeam.java:240)
[20:37:16] [Server thread/WARN]: 	at thaumic.tinkerer.common.item.kami.foci.ItemFocusShadowbeam$Beam.updateUntilDead(ItemFocusShadowbeam.java:253)
[20:37:16] [Server thread/WARN]: 	at thaumic.tinkerer.common.item.kami.foci.ItemFocusShadowbeam.onUsingFocusTick(ItemFocusShadowbeam.java:57)
[20:37:16] [Server thread/WARN]: 	at thaumcraft.common.items.wands.ItemWandCasting.onUsingTick(ItemWandCasting.java:603)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:261)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:393)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:482)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[20:37:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[20:37:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by nekosune** [comment]
Please only test with current versions
