### ISSUE TITLE
infusedSeeds - Internal server error

### ISSUE THREAD

**Issue by rlemish** [Thaumic-Tinkerer/ThaumicTinkerer#865]
![2016-09-16_22-39-48](https://cloud.githubusercontent.com/assets/17569944/18599122/bc11b466-7c67-11e6-94f9-f007851987e0.png)
![2016-09-16_22-42-40](https://cloud.githubusercontent.com/assets/17569944/18599121/bc0f0518-7c67-11e6-83da-b77431698900.png)

**Comment by nekosune** [comment]
We need the actual log, not pictures of the log, and versions.

**Comment by rlemish** [comment]
[Thermos 58](https://github.com/CyberdyneCC/Thermos/releases), [2.5-1.7.10-538](https://github.com/gamerforEA/ThaumicTinkerer-FakePlayers/releases) 

`[21:27:49] [Server thread/WARN]: Failed to handle packet for /128.72.166.38:49273
java.lang.NullPointerException
	at thaumic.tinkerer.common.block.BlockInfusedGrain.getDrops(BlockInfusedGrain.java:132) ~[BlockInfusedGrain.class:?]
	at net.minecraft.block.Block.func_149690_a(Block.java:664) ~[aji.class:?]
	at net.minecraft.block.BlockCrops.func_149690_a(BlockCrops.java:148) ~[akf.class:?]
	at net.minecraft.block.Block.func_149697_b(Block.java:657) ~[aji.class:?]
	at net.minecraft.block.Block.func_149636_a(Block.java:988) ~[aji.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:367) ~[mx.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:244) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:742) ~[nh.class:?]
	at modfixng.nms.packets.v1_7_R4.BlockDig.func_148833_a(BlockDig.java:45) ~[?:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[21:27:49] [Server thread/INFO]: BrightSpine lost connection: Internal server error`

**Comment by nekosune** [comment]
Please test with actual Thaumic Tinkerer, not versions edited by other people

**Comment by rlemish** [comment]
The interaction of objects with region (WorldGuard) forces us to use a modified version.
It is strange that you do not want to support's Event.
thnx!

**Comment by nekosune** [comment]
The trouble is, using edited versions, throws off everything I can do to debug this, 

For example, the line in your crash error? has nothing that CAN null pointer - https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/1.7-final/src/main/java/thaumic/tinkerer/common/block/BlockInfusedGrain.java#L132

Which means it is pointing to a different line, thanks to the modified code.


The 1.8.9 version of Thaumic Thaumic Tinkerer , will use Thaumcraft's built in fake player more, however  adding it into one at end of life, just introduced more bugs, as you have found
