### ISSUE TITLE
TT3 (1.8.9) Food Talisman spams server console, and saturation level not set

### ISSUE THREAD

**Issue by justicesays** [Thaumic-Tinkerer/ThaumicTinkerer#885]
[00:23:19] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Ticking player
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:379) ~[lf.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[ip.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
        at com.nekokittygames.Thaumic.Tinkerer.common.items.baubles.ItemFoodTalisman$.onWornTick(ItemFoodTalisman.scala:71) ~[ItemFoodTalisman$.class:?]
        at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:38) ~[EventHandlerEntity.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_32_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:459) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1563) ~[pr.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283) ~[wn.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:328) ~[lf.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[ip.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more

**Comment by justicesays** [comment]
Looks like the Item code fails to import the forge functions that includes "setFoodSaturationLevel"
Also seems to be some dodgy calculations in there as well (subtracting a value from itself will always be 0), but those probably wont cause java errors.
