### ISSUE TITLE
Crash on Game Start

### ISSUE THREAD

**Issue by Orinai** [Thaumic-Tinkerer/ThaumicTinkerer#910]
So After several hours of testing I have narrowed down that the crash on game start that I have been experiencing in 1.12.2 is definitely thaumic tinkerer. I've never been the best at interpreting crash reports so I'm not sure exactly what the issue is beyond crashing at start up. I do have a host of other mods installed, but the erro seems to replicate with only TC(beta 16) and TT(alpha) installed.

as follows, I tried to include the relivant portions of the error log. My apologies if i'm spamming or not providing enough information. Well aware the mod is in alpha, just figured it was worth reporting, as I have not seen it reported anywhere else. 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.nekokittygames.thaumictinkerer.common.blocks.ModBlocks$RegistrationHandler.registerTileEntity(ModBlocks.java:75)
	at com.nekokittygames.thaumictinkerer.common.blocks.ModBlocks$RegistrationHandler.registerTileEntities(ModBlocks.java:71)
	at com.nekokittygames.thaumictinkerer.common.blocks.ModBlocks$RegistrationHandler.registerBlocks(ModBlocks.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_366_RegistrationHandler_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by nekosune** [comment]
Hi there, I am sorry but I need the full error, not just part to be able to do anything

**Comment by Orinai** [comment]
Ok, then it's my bad, or rather the twitch launcher adding the wrong forge verion. thanks for the quick response
