### ISSUE TITLE
Unknown crash as result of performing research

### ISSUE THREAD

**Issue by 34638a** [Thaumic-Tinkerer/ThaumicTinkerer#935]
Hi neko,

Just letting you know about a crash that brings down both clients and servers when it happens. May be worth looking into if you have time.
Crash Event: Performing any research from Thaumic Tinkerer, base Thaumcraft is fine.
Repeatable: Yes
Mod pack: All the Mods 3 (version 5.10.0, Forge 14.23.4.2760)
Modifications to the pack:
    Updated:
    - Abyssalcraft 1.9.4.13
    - Thaumcraft 6.1.BETA25
    - The Betweenlands 3.3.13

    Installed:
    - Chance Cubes 3.2.2.237
    - Immersive Railroading 1.3.3
    - Thaumic Additions: Reconstructed 5r
    - Thaumic JEI 1.5.4-22

**Comment by Xobra** [comment]
Do you have a crashlog? If yes, upload it to something like pastbin (since crashlogs are long), and post the link here

**Comment by 34638a** [comment]
Relevant Details to the crash are below
- Iam34368a

[00:47:10] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1151) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at thaumcraft.client.gui.GuiResearchPage.drawRequirements(GuiResearchPage.java:611) ~[GuiResearchPage.class:?]
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:453) ~[GuiResearchPage.class:?]
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:328) ~[GuiResearchPage.class:?]
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:268) ~[GuiResearchPage.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) ~[buq.class:?]
	... 9 more
[00:47:10] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Wizardry Plugin (wizardry-0.9.7.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  LoadingPlugin (Quark-r1.5-129.jar)
  HCASM (HammerCore-1.12.2-2.0.3.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.13-core.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  FMLPlugin (elulib-0.1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b156.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)
  RandomPatches (randompatches-1.12.2-1.5.0.4.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 10/27/18 12:47 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at thaumcraft.client.gui.GuiResearchPage.drawRequirements(GuiResearchPage.java:611)
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:453)
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:328)
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:268)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.gui.GuiResearchPage.drawRequirements(GuiResearchPage.java:611)
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:453)
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:328)
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:268)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: thaumcraft.client.gui.GuiResearchPage
	Mouse location: Scaled: (360, 208). Absolute: (1081, 375)
	Screen size: Scaled: (640, 334). Absolute: (1920, 1001). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Iam34638a'/378225, l='MpServer', x=-521.22, y=68.00, z=686.58]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-424,73,508), Chunk: (at 8,4,12 in -27,31; contains blocks -432,0,496 to -417,255,511), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 73887972 game time, 7872951 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityItem['item.item.arrow'/383111, l='MpServer', x=-474.90, y=70.00, z=698.25],
