### ISSUE TITLE
I need some help. I'm new to this site so please be nice

### ISSUE THREAD

**Issue by SomeCurlyHelper** [Thaumic-Tinkerer/ThaumicTinkerer#984]
So I was going to play Minecraft with some mods that I decided to play with and i got this crash report. I know how to change the config ids, but it keeps saying that I've got ars magica 2 which I don't am2 isn't on 1.12.2. I was just wondering if anyone can help.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/24/19 7:57 AM
Description: Initializing game

java.lang.IllegalArgumentException: Duplicate enchantment id! class electroblob.wizardry.enchantment.EnchantmentMagicSword and class am2.enchantments.EnchantMagicResist Enchantment ID:100
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
	at net.minecraft.enchantment.EnchantmentDamage.<init>(SourceFile:33)
	at electroblob.wizardry.enchantment.EnchantmentMagicSword.<init>(EnchantmentMagicSword.java:15)
	at electroblob.wizardry.Wizardry.preInit(Wizardry.java:567)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
	at net.minecraft.enchantment.EnchantmentDamage.<init>(SourceFile:33)
	at electroblob.wizardry.enchantment.EnchantmentMagicSword.<init>(EnchantmentMagicSword.java:15)
	at electroblob.wizardry.Wizardry.preInit(Wizardry.java:567)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 383160704 bytes (365 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCH	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCH	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
	UCH	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCH	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCH	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCH	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (Gilded-Games-Util-1.7.10.jar) 
	UCH	abyssalcraft{1.9.1.3} [AbyssalCraft] (AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar) 
	UCH	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-1.7.10.jar) 
	UCH	ActuallyAdditions{1.7.10-r21} [Actually Additions] (Actually-Additions-Mod-1.7.10.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-Mod-1.7.10.jar) 
	UCH	adventurersamulets{1.7.10-1.2.0c} [Adventurer's Amulets] (Adventurers-Amulets-Mod-1.7.10.jar) 
	UCH	mdxlib{1.0.0.74} [mdxlib] (MDXLib-1.7.10.jar) 
	UCH	avp{4.0.0.822} [AliensVsPredator] (Aliens-vs-Predator-Mod-1.7.10.jar) 
	UCH	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10.jar) 
	UCH	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (Applied-Energistics-2-Mod-1.7.10.jar) 
	UCH	arsmagica2{1.4.0.009} [Ars Magica 2] (Ars-Magica-2-Mod-1.7.10.jar) 
	UCH	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCH	baublesstuff{2.1.2} [Baubles Stuff] (baublesstuff-2.1.2.jar) 
	UCH	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (Blood-Magic-Mod-1.7.10.jar) 
	UCH	Botania{r1.8-249} [Botania] (Botania-Mod-1.7.10.jar) 
	UCH	chisel{2.9.5.11} [Chisel] (Chisel-Mod-1.7.10.jar) 
	UCH	CoroAI{v1.0} [CoroAI] (CoroUtil-1.7.10.jar) 
	UCH	BuildMod{v1.0} [Build Mod] (CoroUtil-1.7.10.jar) 
	UCH	CoroPets{v1.0} [CoroPets] (CoroUtil-1.7.10.jar) 
	UCH	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.7.10.jar) 
	UCH	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.7.10.jar) 
	UCH	cpc{1.7.x-r76.6c6e88f} [CreepyPastaCraft] (CreepyPastaCraft-Revived-Mod-1.7.10.jar) 
	UCH	D3Core{1.1.2.41} [D3Core] (D3Core-1.7.10.jar) 
	UCH	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCH	Enchiridion{1.3} [Enchiridion] (Enchiridion-1.7.10.jar) 
	UCH	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion-1.7.10.jar) 
	UCH	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	UCH	fusionutil{0.1} [FusionUtil] (FusionUtil-1.7.10.jar) 
	UCH	GalacticraftCore{3.0.12} [Galacticraft Core] (Galacticraft-Mod-1.7.10.jar) 
	UCH	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCH	GraviGun{4.0.0-beta} [GraviGun] (Gravity-Gun-Mod-1.7.10.jar) 
	UCH	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (HarvestCraft-Mod-1.7.10.jar) 
	UCH	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UCH	journeymap{4.0.1} [JourneyMap] (JourneyMap-Mod-1.7.10-FairPlay.jar) 
	UCH	Lumberjack{1.1.0.21} [Lumberjack] (Lumberjack-mod-by-doubledoor-1.7.10.jar) 
	UCH	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (Lycanites-Mobs-Mod-1.7.10.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-Mod-1.7.10.jar) 
	UCH	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10.jar) 
	UCH	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCH	oreexcavation{1.1.134} [OreExcavation] (Ore-Excavation-Mod-1.7.10.jar) 
	UCH	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10.jar) 
	UCH	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-Mod-1.7.10.jar) 
	UCH	rftools{4.23} [RFTools] (RFTools-Mod-1.7.10.jar) 
	UCH	rpgloot{1.0} [RPG Loot] (RPGLoot-Mod-1.7.10.jar) 
	UCH	runesofwizardry{1.7.10-0.3.1} [Runes of Wizardry] (Runes-of-Wizardry-Mod-1.7.10.jar) 
	UCH	SaintsCore{0.9} [Saintscore] (SaintsCore-0.9-Minecraft-1.7.10.jar) 
	UCH	mod_Saintspack{0.9} [Saintspack] (SaintsPack-0.9-Minecraft_1.7.10) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
	UCH	Techguns{0.1.0} [Techguns] (Techguns-Mod-1.7.10.jar) 
	UCH	thaumicenergistics{1.1.3.0} [Thaumic Energistics] (thaumicenergistics-1.1.3.0.jar) 
	UCH	ThaumicEquivalence{1.7.10-1.0.4} [Thaumic Equivalence] (ThaumicEquivalence-1.7.10-1.0.4.jar) 
	UCH	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCH	TMechworks{0.2.15.106} [Tinkers' Mechworks] (Tinkers-Mechworks-Mod-1.7.10.jar) 
	UCH	TragicMC{2.46.2878} [TragicMC 2] (TragicMC2-1.7.10-2.46.2878.jar) 
	UCH	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCH	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCE	wizardry{1.1.5} [Electroblob's Wizardry] (Wizardry-Mod-1.7.10.jar) 
	UCH	ZAMod{v1.10} [Zombie Awareness] (Zombie-Awareness-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11020.2003' Renderer: 'Radeon RX 570 Series'
	CoFHCore: -[1.7.10]3.1.3-327
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Radeon RX 570 Series GL version 4.5.13521 Compatibility Profile Context 24.20.11020.2003, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13521 Compatibility Profile Context 24.20.11020.2003
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by SomeCurlyHelper** [comment]
I'm new here so I don't really know where to put this but if anyone would be willing to help please tell me. I've tried deleting the config folder but it didn't help

**Comment by SomeCurlyHelper** [comment]
It's okay, thank you to anyone who looks at this. I hope you all have a good day
